spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000

#server:
#  compression:
#    enabled: true
#  servlet:
#    context-path: /api
#  port: 443
#  ssl:
#    key-store: classpath:404z.cn.jks
#    key-store-password: ChengKai1998!
#    key-store-type: JKS

logging:
  file:
    name: /log/demo-mysql2.log

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.entity
  configuration:
    map-underscore-to-camel-case: true

id:
  machine-id: 0
  machine-bits: 8
  sequence-bits: 12
