#server:
#  servlet:
#    context-path: /api
#  port: 443
#  ssl:
#    key-store: classpath:k3t3.com.pfx
#    key-store-password: 40I69DfH
#    key-store-type: PKCS12
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_api_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: chengkai
  rabbitmq:
    host: localhost
    port: 5672
    username: ali
    password: ali
    virtual-host: ali
  data:
    mongodb:
      host: localhost
      database: ali
      port: 27017
  mail:
    host: smtp.qq.com
    username: 1416978277@qq.com
    password: akaipgfscehfghci
    protocol: smtp
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.demo.entity
#  configuration:
#    map-underscore-to-camel-case: true
logging:
  file:
    name: /log/springboot-api-demo.log
  level:
    root: info
    com:
      demo:
        mapper: trace
id:
  machine-id: 0
  machine-bits: 8
  sequence-bits: 12
ansj:
  default-resource-path: /file/ansj/default.dic
  ambiguity-resource-path: /file/ansj/ambiguity.dic
ip2region:
  resource-path: /file/ip2region/data.db
  reference-path: /file/ip2region/data.db