spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  mail:
    host: smtp.qq.com
    username: 1416978277@qq.com
    password: akaipgfscehfghci

#server:
#  compression:
#    enabled: true
#  servlet:
#    context-path: /api
#  port: 443
#  ssl:
#    key-store: classpath:404z.cn.jks
#    key-store-password: ChengKai1998!
#    key-store-type: JKS

logging:
  file:
    name: /log/demo-base.log
